on:
  pull_request:
    branches: master

name: R-linux-pr

env:
  R_REMOTES_NO_ERRORS_FROM_WARNINGS: true
  SLACK_API_TOKEN: ${{ secrets.SLACK_API_TOKEN }}
  SLACK_SKIPLOAD: ${{ secrets.SLACK_SKIPLOAD }}
  GITHUB_PAT: ${{ secrets.GH_PAT }}

jobs:

  setup:
    strategy:
      fail-fast: false

    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, 'linux nocache')"

    steps:

      - uses: actions/checkout@v2

      - uses: r-lib/actions/setup-pandoc@v2

      - uses: r-lib/actions/setup-r@v2
        with:
          r-version: release
          use-public-rspm: true

      - uses: r-lib/actions/setup-r-dependencies@v2
        with:
          extra-packages: any::rcmdcheck
          needs: check
  check:
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, 'linux nocheck')"
    steps:

      - uses: actions/checkout@v2

      - uses: r-lib/actions/setup-pandoc@v2

      - uses: r-lib/actions/setup-r@v2
        with:
          r-version: release
          use-public-rspm: true

      - uses: r-lib/actions/setup-r-dependencies@v2
        with:
          extra-packages: any::rcmdcheck
          needs: check

      - uses: r-lib/actions/check-r-package@v2
        with:
          upload-snapshots: true


  dispatches:
    needs: [check]
    runs-on: ubuntu-latest
    steps:
      - name: slackthreads trigger
        uses: peter-evans/repository-dispatch@v1.0.0
        with:
          token: ${{secrets.GH_PAT}}
          repository: yonicd/slackthreads
          event-type: push
          client-payload: '{"repository": "${{ github.repository }}", "ref": "${{ github.ref }}", "sha": "${{ github.sha }}"}'

      - name: slackblocks trigger
        uses: peter-evans/repository-dispatch@v1.0.0
        with:
          token: ${{secrets.GH_PAT}}
          repository: yonicd/slackblocks
          event-type: push
          client-payload: '{"repository": "${{ github.repository }}", "ref": "${{ github.ref }}", "sha": "${{ github.sha }}"}'
