on: [push]

name: R-mac

env:
  R_REMOTES_NO_ERRORS_FROM_WARNINGS: true
  SLACK_API_TOKEN: ${{ secrets.SLACK_API_TOKEN }}
  SLACK_SKIPLOAD: ${{ secrets.SLACK_SKIPLOAD }}
  GITHUB_PAT: ${{ secrets.GH_PAT }}


jobs:

  setup:
    runs-on: ubuntu-latest
    outputs:
      cache-status: ${{ steps.test-output.outputs.my_value }}

    steps:

      - name: cache-R-dir
        uses: actions/cache@v2
        with:
          path: |
            ./R
          key: check-files-${{ hashFiles('R/**') }}

      - id: test-output
        run: echo "::set-output name=my_value::hello"

      - name: Display
        run: echo "${{ steps.test-output.outputs.my_value }}"

  eval:
    runs-on: ubuntu-latest
    needs: setup

    steps:
      - name: checkme
        run: echo "${{ needs.setup.outputs.cache-status }}"

