on: [push]

name: R-mac

env:
  R_REMOTES_NO_ERRORS_FROM_WARNINGS: true
  SLACK_API_TOKEN: ${{ secrets.SLACK_API_TOKEN }}
  SLACK_SKIPLOAD: ${{ secrets.SLACK_SKIPLOAD }}
  GITHUB_PAT: ${{ secrets.GH_PAT }}


jobs:

  setup:
    strategy:
      fail-fast: false
    outputs:
      cache_status: ${{ steps.cache-R-dir.outputs.cache-hit }}
    runs-on: ubuntu-latest

    steps:

      - uses: actions/checkout@v2

      - name: cache-R-dir
        uses: actions/cache@v2
        with:
          path: |
            ./R
          key: check-files-${{ hashFiles('R/**') }}

      - name: test-output
        run: "::set-output name=my_value::hello"

  eval:
    runs-on: ubuntu-latest
    needs: setup
    steps:
      - name: checkme
        run: echo "${{ needs.setup.outputs.test-output }}"

