on: [push]

name: R-mac

env:
  R_REMOTES_NO_ERRORS_FROM_WARNINGS: true
  SLACK_API_TOKEN: ${{ secrets.SLACK_API_TOKEN }}
  SLACK_SKIPLOAD: ${{ secrets.SLACK_SKIPLOAD }}
  GITHUB_PAT: ${{ secrets.GH_PAT }}


jobs:

  setup:
    strategy:
      fail-fast: false
    outputs:
      dirs_unchanged: ${{ steps.cache-dirs.outputs.cache-hit }}
    runs-on: macOS-latest
    if: "!contains(github.event.head_commit.message, 'osx nocache')"

    steps:

      - uses: actions/checkout@v2

      - uses: r-lib/actions/setup-pandoc@v2

      - uses: r-lib/actions/setup-r@v2
        with:
          r-version: release
          use-public-rspm: true

      - id: cache-dirs
        uses: actions/cache@v2
        with:
          path: |
            ./R
            ./DESCRIPTION
            ./tests
          key: check-files-${{ hashFiles('R/**') }}-${{ hashFiles('DESCRIPTION') }} -${{ hashFiles('tests/**') }}

      - uses: r-lib/actions/setup-r-dependencies@v2
        with:
          extra-packages: any::rcmdcheck
          needs: check

  check:
    runs-on: macOS-latest
    needs: setup
    if: needs.setup.outputs.dirs_unchanged != 'true'

    steps:

      - uses: actions/checkout@v2

      - uses: r-lib/actions/setup-pandoc@v2

      - uses: r-lib/actions/setup-r@v2
        with:
          r-version: release
          use-public-rspm: true

      - uses: r-lib/actions/setup-r-dependencies@v2
        with:
          extra-packages: any::rcmdcheck
          needs: check

      - uses: r-lib/actions/check-r-package@v2
        with:
          upload-snapshots: true
