on: [pull_request]

name: R-mac-pr

jobs:
  check:
    runs-on: ${{ matrix.config.os }}
    name: ${{ matrix.config.os }} (${{ matrix.config.r }})

    strategy:
      fail-fast: false
      matrix:
        config:
        - { os: macOS-latest, r: '4.0', args: "--no-manual"}

    env:
      R_REMOTES_NO_ERRORS_FROM_WARNINGS: true
      CRAN: ${{ matrix.config.cran }}
      SLACK_API_TOKEN: ${{ secrets.SLACK_API_TOKEN }}
      SLACKR_TOKEN: ${{ secrets.SLACKR_TOKEN }}
      SLACKR_MEMBERID: ${{ secrets.SLACKR_MEMBERID }}

    steps:
      - uses: actions/checkout@master

      - uses: r-lib/actions/setup-tinytex@master
        if: contains(matrix.config.args, 'no-manual') == false

      - uses: r-lib/actions/setup-pandoc@master

      - uses: r-lib/actions/setup-r@master
        with:
          r-version: ${{ matrix.config.r }}

      - name: Cache R packages
        uses: actions/cache@v1
        with:
          path: ${{ env.R_LIBS_USER }}
          key: ${{ runner.os }}-r-${{ matrix.config.r }}-${{ hashFiles('DESCRIPTION') }}

      - name: Install dependencies
        run: Rscript -e "install.packages('remotes')" -e "remotes::install_deps(dependencies = TRUE)" -e "remotes::install_cran('rcmdcheck')"

      - name: Check
        run: Rscript -e "rcmdcheck::rcmdcheck(args = '${{ matrix.config.args }}', error_on = 'warning', check_dir = 'check')"

      - name: slackthreads trigger
        if: github.ref == 'refs/heads/master'
        uses: peter-evans/repository-dispatch@v1.0.0
        with:
          token: ${{secrets.GITHUB_PAT}}
          repository: yonicd/slackthreads
          event-type: push
          client-payload: '{"repository": "${{ github.repository }}", "ref": "${{ github.ref }}", "sha": "${{ github.sha }}"}'

      - name: slackblocks trigger
        if: github.ref == 'refs/heads/master'
        uses: peter-evans/repository-dispatch@v1.0.0
        with:
          token: ${{secrets.GITHUB_PAT}}
          repository: yonicd/slackblocks
          event-type: push
          client-payload: '{"repository": "${{ github.repository }}", "ref": "${{ github.ref }}", "sha": "${{ github.sha }}"}'
