on: [push]

name: R-mac

env:
  R_REMOTES_NO_ERRORS_FROM_WARNINGS: true
  SLACK_API_TOKEN: ${{ secrets.SLACK_API_TOKEN }}
  SLACK_SKIPLOAD: ${{ secrets.SLACK_SKIPLOAD }}
  GITHUB_PAT: ${{ secrets.GH_PAT }}


jobs:

  setup:
    strategy:
      fail-fast: false

    runs-on: macOS-latest
    name: macOS-latest (4.0)
    if: "!contains(github.event.head_commit.message, 'skip osx')"

    steps:

      - uses: actions/checkout@v2

      - uses: r-lib/actions/setup-tinytex@master

      - uses: r-lib/actions/setup-pandoc@v2

      - uses: r-lib/actions/setup-r@v2
        with:
          r-version: release
          use-public-rspm: true

      - uses: r-lib/actions/setup-r-dependencies@v2
        with:
          extra-packages: any::rcmdcheck
          needs: check

  check:
    needs: setup
    runs-on: macOS-latest
    steps:
      - uses: r-lib/actions/check-r-package@v2
        with:
          upload-snapshots: true
