on: [push]

name: R-mac

env:
  R_REMOTES_NO_ERRORS_FROM_WARNINGS: true
  SLACK_API_TOKEN: ${{ secrets.SLACK_API_TOKEN }}
  SLACK_SKIPLOAD: ${{ secrets.SLACK_SKIPLOAD }}
  GITHUB_PAT: ${{ secrets.GH_PAT }}


jobs:

  setup:
    runs-on: ubuntu-latest
    outputs:
      dummy: ${{ steps.test-output.outputs.my_value }}
      cache_status: ${{ steps.cache-R-dir.outputs.cache-hit }}

    steps:
      - uses: actions/checkout@v2

      - id: cache-R-dir
        uses: actions/cache@v2
        with:
          path: |
            ./R
          key: check-files-${{ hashFiles('R/**') }}

      - id: test-output
        run: echo "::set-output name=my_value::hello"

      - name: Display Dummy
        run: echo "${{ steps.test-output.outputs.my_value }}"

      - name: Display Cache Hit
        run: echo "${{ steps.cache-R-dir.outputs.cache-hit }}"

  eval:
    runs-on: ubuntu-latest
    needs: setup

    steps:
      - name: dummy check
        run: echo "${{ needs.setup.outputs.dummy }}"
      - name: cache check
        run: echo "${{ needs.setup.outputs.cache-check }}"
