on: [push]

name: R-winos

env:
  R_REMOTES_NO_ERRORS_FROM_WARNINGS: true
  SLACK_API_TOKEN: ${{ secrets.SLACK_API_TOKEN }}
  SLACK_SKIPLOAD: ${{ secrets.SLACK_SKIPLOAD }}
  GITHUB_PAT: ${{ secrets.GH_PAT }}


jobs:

  setup:
    strategy:
      fail-fast: false

    runs-on: windows-latest
    if: "!contains(github.event.head_commit.message, 'winos nocache')"

    steps:

      - uses: actions/checkout@v2

      - uses: r-lib/actions/setup-pandoc@v2

      - uses: r-lib/actions/setup-r@v2
        with:
          r-version: release
          use-public-rspm: true

      - uses: r-lib/actions/setup-r-dependencies@v2
        with:
          extra-packages: any::rcmdcheck
          needs: check

  check:
    runs-on: windows-latest
    if: "!contains(github.event.head_commit.message, 'winos nocheck')"
    steps:

      - uses: actions/checkout@v2

      - uses: r-lib/actions/setup-pandoc@v2

      - uses: r-lib/actions/setup-r@v2
        with:
          r-version: release
          use-public-rspm: true

      - uses: r-lib/actions/setup-r-dependencies@v2
        with:
          extra-packages: any::rcmdcheck
          needs: check

      - uses: r-lib/actions/check-r-package@v2
        with:
          upload-snapshots: true
